[tool.poetry]
name = "urls"
version = "0.1.0"
description = ""
authors = ["romanlosev <losik19-94@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
